### ISSUE TITLE
Centrifuge app feedback 

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1271]
## Background
While testing the app, we gathered some feedback for some smaller fixes.

## Feedback
- [x] Currently Pools created on the Centrifuge Chain are ordered by `Investment capacity`. 
- [x]  Pools created on Ethereum ... is still an open question
![Screenshot 2023-03-23 at 19 00 55](https://user-images.githubusercontent.com/31280003/227303252-7ad6f007-5c9d-4621-a829-98fd0cbca0a8.png)
* On the Configuration page, if there are already some issuer profile sections, when I click Edit they don’t show up at all. I can only add more sections but not edit the existing ones. See https://app-demo.k-f.dev/issuer/390255799/configuration
![Screenshot 2023-03-23 at 19 21 12](https://user-images.githubusercontent.com/31280003/227310793-48078c4a-c413-4dbb-8b5c-2a07bf3cd10c.png)

* Looking at https://app-dev.k-f.dev/pools/3152960027/liquidity, it seems like the Repayments & originations and Investments & redemptions charts are grouped by epoch still, but now displaying the closed date of each epoch rather than the epoch ID. I think this should actually be grouped by day instead.
- [x] The Bridge Fund Series 1 is overlapping on two lines because it’s too long. I would probably suggest just limiting it at a certain length and adding ….
![Screenshot 2023-03-23 at 19 18 57](https://user-images.githubusercontent.com/31280003/227310177-458ca192-421b-4fa2-82ff-186b57dbfcea.png)

## Changes
- [x]  Research how pools created on Ethereum are ordered 
- [x]  All pools created on Ethereum and Centrifuge Chain should be ordered by `Value locked` 
- [x] Starting with the highest value locked and then sorted downward

* Enable editing of the Issuer profile sections 
* Repayments & originations and Investments & redemptions charts can be queried from the subquery using the poolSnapshots  entities instead of the epoches entities, I think we actually have the data already in this method: https://github.com/centrifuge/apps/blob/main/centrifuge-js/src/modules/pools.ts#L1557)

- [x]  Limiting the pool name on the lefthand side at a certain length on the left hand side and adding ….

**Comment by Hornebom** [comment]
Sorting of pools is resolved in [1276](https://github.com/centrifuge/apps/pull/1276)

**Comment by Hornebom** [comment]
Preventing pool links wrapping into new lines is resolved in [1279](https://github.com/centrifuge/apps/pull/1279)

**Comment by annamehr** [comment]
> On the Configuration page, if there are already some issuer profile sections, when I click Edit they don’t show up at all. I can only add more sections but not edit the existing ones. See https://app-demo.k-f.dev/issuer/390255799/configuration

I just tested adding more issuer information after pool has been created and I received a notification that it was saved but then it does not appear on the screen. See my video


https://user-images.githubusercontent.com/31280003/229083042-517dc061-ca7c-4ece-b20b-445bce26733f.mov

**Comment by offerijns** [comment]
> Looking at https://app-dev.k-f.dev/pools/3152960027/liquidity, it seems like the Repayments & originations and Investments & redemptions charts are grouped by epoch still, but now displaying the closed date of each epoch rather than the epoch ID. I think this should actually be grouped by day instead.

I don't think this was one was addressed yet @Hornebom ?

**Comment by annamehr** [comment]
Yes, plus the  `Enable editing of the Issuer profile sections ` is also still missing. @Hornebom I didn't create new tickets for the two outstanding todos and that's why I reopened this issue.

**Comment by annamehr** [comment]
@offerijns I talked with Ben about this ticket today. On the x-axis the days are displayed based on when the epoch was closed right now. When you say epoch ID, do you refer to the day when the epoch was opened?
Or which value did you propose to display on the x-axis? 
<img width="506" alt="Screenshot 2023-04-13 at 12 36 19" src="https://user-images.githubusercontent.com/31280003/231733790-eb3782bb-afb1-4558-b837-2377c1abc289.png">

**Comment by Hornebom** [comment]
@annamehr Edit functionality of the pool details: https://github.com/centrifuge/apps/pull/1324
