### ISSUE TITLE
Product Feedback on new designs

### ISSUE THREAD

**Issue by kattylucy** [centrifuge/apps#2471]
I created this ticket for product to use as the placeholder and add the feedback during testing. 

**What are we testing?** 

Landing page (/pools)
Pool overview page (/pools/:poolId)
Reports page (pools/reporting/)
Data page (pools/data)

**Comment by 0x4Graham** [comment]
Hey!

Looks like updating the Target APY isn't working: 
<img width="855" alt="image" src="https://github.com/user-attachments/assets/2e8df4af-c42d-4e70-a6a8-10740cfebcf0">
<img width="331" alt="image" src="https://github.com/user-attachments/assets/f7b2bf64-311f-40c1-af7a-fa6b20c06fff">

Never updated
<img width="1119" alt="image" src="https://github.com/user-attachments/assets/aa77edc2-f9f9-48f4-a3ca-f0fb98631682">

**Comment by 0x4Graham** [comment]
<img width="175" alt="image" src="https://github.com/user-attachments/assets/dddd80fe-3218-496b-8870-9fa0c99427ca">
Very very difficult to click on this

**Comment by sonam-jo** [comment]
For funds that have only 1 tranche, we should just have the name of the fund under Token, and Token price in the chart -- no `junior` -- same as the UI today
![Screenshot 2024-10-04 at 13 14 15](https://github.com/user-attachments/assets/ed4b3380-eb46-4243-bdb7-592a8ba3ecf0)
![Screenshot 2024-10-04 at 13 13 16](https://github.com/user-attachments/assets/98dbf33d-56ed-44f4-9ecb-4eb5615c6127)

**Comment by sonam-jo** [comment]
Axis for APY chart looks off -- it neither is the same for all time windows, nor does it adjust to show the graph properly with different time windows

![Screenshot 2024-10-04 at 13 16 14](https://github.com/user-attachments/assets/44e068a6-a9e6-4e8a-b232-a44aba519b4d)
![Screenshot 2024-10-04 at 13 16 23](https://github.com/user-attachments/assets/0d6ff294-afe4-479c-9df5-588f3376c820)
![Screenshot 2024-10-04 at 13 16 33](https://github.com/user-attachments/assets/bf80e1c0-9e7d-4fa8-a478-3ea2c3d4eba2)

**Comment by sonam-jo** [comment]
The only item missing from this Overview box is Expense ratio. 
1. Expense ratio is something we calculate, and should appear in every fund we create as long as we have the fees numbers and the NAV. 
2. There is a lot of blank space in the overview box. I would recommend increasing the spacing across the rows in line with Figma, and perhaps reducing the side of the chart so there is less white space on the page.
3. There seems to be a difference in the font size for the titles (e.g. Asset type) and the respective fields (e.g. Private credit)

![Screenshot 2024-10-04 at 13 19 33](https://github.com/user-attachments/assets/a79d5c5e-107a-47d5-abba-084cc9e04809)

**Comment by 0x4Graham** [comment]
Create pool button has the wrong colour 
<img width="297" alt="image" src="https://github.com/user-attachments/assets/897df5a3-65d1-493f-b9ec-3fb8d19abd6a">

**Comment by 0x4Graham** [comment]
When creating a pool, the APR for the tranche is also not set: 

<img width="1485" alt="image" src="https://github.com/user-attachments/assets/815436d6-1981-418a-bcf3-9d47e5e4c45b">

**Comment by 0x4Graham** [comment]
When creating the pool, I only named the token "Twirl". 

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/29612561-f713-4208-b816-ffd9f6ced6b0">


But the token name in the display is: Twirl Junior junior. Which shouldn't be the case.

**Comment by kattylucy** [comment]
The expense ratio is there but probably for this specific pool is 0 so it does not show. 

For the APY, can you give me a bit more context on what do you mean? The filter is changing the APY based on if 30 days, 90 days, YTD. is this not what we want? 

![Image](https://github.com/user-attachments/assets/8161a03c-fe01-40cd-8b37-2f8f48041fd6)


@sonam-jo

**Comment by hieronx** [comment]
Overall it looks amazing, really nice job @kattylucy ! Excited to see this go live soon.

I have quite a list of QA feedback, but they are almost all very small points :) 

### Landing page
- The full card should be clickable, now the white space at the bottom half isn't.
<img width="383" alt="Screenshot 2024-10-09 at 11 34 03" src="https://github.com/user-attachments/assets/14398e3c-d38f-4234-a1e7-1ced2d3ae9ea">

- The ordering of the tranches should be senior at the top, rather than junior at the top.

- For the min investment fields, the prefix `$` sign is missing.

- The color gray of the `Total value locked (TVL)` heading seems too light (#cfcfcf vs #82888D in design).

- There should be more padding on the right side of the Governance submenu:
<img width="822" alt="Screenshot 2024-09-02 at 14 28 33" src="https://github.com/user-attachments/assets/0416eec2-0221-496e-aef8-9187fe6cd181">

- The padding on the top seems a bit off compared to the design. In the implementation, the top padding is less than the left padding:
<img width="193" alt="Screenshot 2024-10-09 at 11 39 15" src="https://github.com/user-attachments/assets/e2c2c681-1945-48ec-9188-da2195788590">

While in the design, it is about the same:
<img width="153" alt="Screenshot 2024-10-09 at 11 39 18" src="https://github.com/user-attachments/assets/dc813766-360f-4f56-a80c-e23eb4b42029">

- Nits:
  - `Asset Type` => `Asset type`
  - `Min Investment` => `Min. investment`
  - `Tranches` => `Tranche`


### Pool overview
- The expense ratio should be the sum of all the fees in the pool. So for Anemoy LTF, the number should be 0.15%. It is now incorrectly showing as 1.20% instead.

- In the Reports section, none of the buttons have a hover action. I think it would be good to add this.
<img width="508" alt="Screenshot 2024-10-09 at 11 33 23" src="https://github.com/user-attachments/assets/235536ff-0a78-4524-946e-d26190cc645c">

- The font size of the expense ratio tooltips appears too small:
<img width="267" alt="Screenshot 2024-10-09 at 11 40 44" src="https://github.com/user-attachments/assets/af75188f-994d-48e8-a4e1-a25f05feb319">

In the design it is 12px.

- Nits:
  - `Expense Ratio` => `Expense ratio`
  - `Cashflow statement` => `Cash flow statement`
  - `Executive Summary` => `Executive summary`

**Comment by sonam-jo** [comment]
For the Transaction history table in the overview page, two changes:
- change `Principal payment` to `Sale`
- more description of the actions: e.g for the highlighted section in the screenshot, it should say Sale of [912797LK1](https://pr2473-app-ff-production.k-f.dev/pools/4139607887/data/token-price?debug#/pools/4139607887/assets/10), settled into [Brokerage account](https://pr2473-app-ff-production.k-f.dev/pools/4139607887/data/token-price?debug#/pools/4139607887/assets/12)

![Screenshot 2024-10-09 at 16 12 33](https://github.com/user-attachments/assets/f10db9c7-baf5-4601-9e67-9fa63c3a6a4e)

**Comment by hieronx** [comment]
- To add to @sonam-jo 's comment above, we should also fix the correction transactions:
<img width="1108" alt="Screenshot 2024-10-10 at 21 25 38" src="https://github.com/user-attachments/assets/66e2d4f2-5223-4e8f-90fd-922fa6e17fa8">

These should display as `Correction ↑ of Brokerage account` (for a correction up), or `Correction ↓ of Brokerage account` (for a correction up), and Brokerage account should be a link.

- I would add $ prefix here too, to be consistent with the landing page:
<img width="482" alt="Screenshot 2024-10-10 at 21 26 45" src="https://github.com/user-attachments/assets/5968060f-c5ab-4ff8-a7d6-6af1a1c195be">

- On the Reports page, can we make the bars (significantly) wider, if you have selected a longer period like monthly?
<img width="1495" alt="Screenshot 2024-10-10 at 21 27 17" src="https://github.com/user-attachments/assets/2be9edaf-f31a-4e74-9bb9-3504baed8974">

Similar to how the 30 day view on the pool overview chart also has wider bars than the longer time views:
<img width="956" alt="Screenshot 2024-10-10 at 21 27 40" src="https://github.com/user-attachments/assets/be407997-99e5-42e4-840f-dcbe0b65d52c">

**Comment by hieronx** [comment]
One more thing I noticed in the transaction history: the cash transfer here (on the bottom of the table for Anemoy LTF) should be from another account (Transfer account I think) to the Brokerage account, not from Brokerage account to Brokerage account. I think the `assetFrom` rather than `asset` should be used for the left side here.

<img width="1505" alt="Screenshot 2024-10-11 at 09 46 27" src="https://github.com/user-attachments/assets/b792d6e2-cca0-49bc-93b5-f544cc4265b5">

**Comment by hieronx** [comment]
One more typo: `Investor Type` => `Investor type` on the landing page, within the cards.

**Comment by hieronx** [comment]
On the Liquidity page, I'd make these two buttons secondary/gray, like the Download buttons on the overview page.

<img width="1507" alt="Screenshot 2024-10-11 at 12 02 00" src="https://github.com/user-attachments/assets/5eb2b738-1ecd-46b1-a15f-462657baf3c0">

**Comment by hieronx** [comment]
The Invest button should be fully right aligned, and have some more left & right padding within the button.

Design:

<img width="945" alt="Screenshot 2024-10-11 at 12 02 53" src="https://github.com/user-attachments/assets/00289ee7-a88e-4560-b7e3-2dbbadf74105">

Implementation:

<img width="1486" alt="Screenshot 2024-10-11 at 12 03 04" src="https://github.com/user-attachments/assets/2ec2928e-80ec-45e3-83d7-324416dd601e">

**Comment by sonam-jo** [comment]
### Overview page

**Cosmetic changes**
- I still see junior in the token price for single tranche. it should just say `Token price`
- Shift the spacing around  for the Token/Invest row such that there is more space between `Token` and `APY `and  `Invest` is all the way to the right with a bigger box (similar to the UI)
- Do not show Pool analysis when there isn't any (like with DYF)
- Icons next to the Balance Sheet, CF, P&L should be in grey with more padding between the icon and text


**UX** 
- Currently the CTA is always Invest, when it should follow the logic from the ticket:
```
CTA on the table depends on investor status
- If the wallet is not connected, the CTA should be "Connect" and should open the connect wallet flow. Do not open side panel. 
- If the wallet is connected, but it is not on the memberlist of the fund, then show the "Onboard" button. The onboard button should follow the onboarding flow (i.e Open up new page to Anemoy onboarding). Do not open side panel. 
- If the wallet is connected & is onboarded to the fund but has not previously invested, then show "Invest" CTA. Clicking on the CTA should open the side panel. Side panel should show the renamed "Investment position" and now include Realized and Unrealized P&L. It will also now include the APY in the Price chart. 
- If the wallet is connected & is onboarded to the fund but has previously invested, then show "Invest / Redeem" CTA. Clicking on the CTA should open the side panel to Invest.
```
![Screenshot 2024-10-11 at 11 07 39](https://github.com/user-attachments/assets/347674d7-515f-42e8-a645-535326243f54)

**Comment by sonam-jo** [comment]
### Landing page

UX
- APY on Landing page does not match APY in the Overview pages for DYF and LTF. They should be the same as Overview page. 

Cosmetic
- Font size and spacing for single tranche pools with just APY and Min. investment looks off compared to the designs
- Lighter grey background for `Closed` box
- Can't really see NS2 icon
- Once all the short descriptions are in, check if there is still extra blank space at the bottom of each box. If so, consider reducing the size of the boxes and increase the padding between the top row and bottom row pools

**Comment by hieronx** [comment]
- The name here (Bank account) is now correct, but the link is still incorrect:

<img width="1497" alt="Screenshot 2024-10-11 at 13 42 31" src="https://github.com/user-attachments/assets/580f1713-41a6-4994-82d7-f5b3858a5167">

**Comment by hieronx** [comment]
The right padding of the sub items is now fixed, but the right padding of the chevron of the Governance item is still too little:

<img width="278" alt="Screenshot 2024-10-11 at 15 03 48" src="https://github.com/user-attachments/assets/86ab4e06-5d71-4a92-8820-20dd8d97ccd3">

**Comment by sonam-jo** [comment]
### Reports page

Cosmetic
- Can we fix the first column for all reports such that when the user scrolls to the right, you can still see all the row headings?
- The calendar boxes next to the dates in the chart need to be closer to the dates. Same with the dropdown next to Monthly
- In the table, the grey lines for the rows should be lighter, in line with Figma. (Same with chart?)
- Change the date format in the chart from 11/10/2024 to Oct 11, 2024 (to be in line with the table)
- Boxes around Balance sheet/P&L/CF to be light grey, not black
- Can we have a smaller box for CSV?

**Comment by hieronx** [comment]
- The range should only be shown on the pool overview page. In the card, where the APY is shown per tranche, there should be no range. In this case the Senior APY should just be 4%.

<img width="394" alt="Screenshot 2024-10-14 at 09 59 30" src="https://github.com/user-attachments/assets/654d03c8-2f75-43fa-949e-1f35e98c54b3">

- If no APY is set, `-` should be shown:

<img width="363" alt="Screenshot 2024-10-14 at 10 00 10" src="https://github.com/user-attachments/assets/c5aaf95f-d114-44e8-8668-44bb144e4b83">

**Comment by sonam-jo** [comment]
Yes neither is launch blocking - we can do fixing table columns and date formatting post release.

**Comment by kattylucy** [comment]
Great - I will prepare tickets for those @sonam-jo

**Comment by hieronx** [comment]
@kattylucy a small design change to the sidebar:
- Can you add more padding to the Centrifuge logo so the left and right padding is aligned? Looks like it needs another 8px on top.
- Can you add `rgba(145, 150, 155, 0.13)` as the background color for the active menu item? Also needs `margin-right: 20px; border-radius: 4px;` on the anchor tag.

See sample screenshot of how it should look:

<img width="1796" alt="Screenshot 2024-10-14 at 16 16 44" src="https://github.com/user-attachments/assets/cafcdcbe-9ec6-46de-bf6b-5711541c89dc">

**Comment by BrianCarter-Design** [comment]
Hi @kattylucy I've reviewed done a full design QA on the pages that are in dev so far. I've added a link to the Figma file where I've documented all the feedback. I've noted everything I could find, so most of it is minor and perhaps a low priority, but just thought I would add everything. 
https://www.figma.com/design/ng7qdNcSCXSDA6ZUdWIs6u?node-id=4013-2504#986168970

**Comment by sonam-jo** [comment]
`Start execution order` CTA is showing up on the `Liquidity page` for the 3 Tinlake pools, when logged in as Alice or even when not connected to the wallet. Please remove.

![Screenshot 2024-10-15 at 14 00 47](https://github.com/user-attachments/assets/b21c6cd3-4aa3-4c0f-abc8-d75529fd9d51)

**Comment by sonam-jo** [comment]
For DYF, the APY of 8.95% is incorrect. I've created to investigate this post launch, but for the time being, can we please hardcode `15% target` as APY for both the landing and overview pages.

**Comment by sonam-jo** [comment]
For NS3, we seem to be having the same issue as DYF. Can we please hardcode:

Landing page
`8% target` for Senior
`16% target` for Junior

Overview page
Overview box: `Target APY` with `8% - 16%`
Token table: `8% target` for Senior, and `16% target` for Junior

**Comment by hieronx** [comment]
@kattylucy to this point: https://github.com/centrifuge/apps/issues/2471#issuecomment-2411433372 looks mostly correct now, except the background color is only implemented on hover, but should be always on for the active item (so it shows permanently for that one, not just on hover).

**Comment by sonam-jo** [comment]
Overview page

1) For DYF, can we change the font size in the service providers box so they all fit in 1 line

<img width="819" alt="Screenshot 2024-10-16 at 11 16 16" src="https://github.com/user-attachments/assets/b7d31573-52db-47f2-9688-daa822a18c54">

2) For DYF, keep the title as APY but change to `15% target`

3) For NS3, APYs need to be swapped. Senior is 8% target and Junior is 16% target. Shift the white box of service providers to the centre of the text.

**Comment by sonam-jo** [comment]
For the Tinlake pools, when clicking on Onboard -- its taking user to the Onboarding flow when users can no longer invest in them. For these 3 closed pools, please change the CTA to `Closed` instead
